/* 
 * Stationsdatenbereitstellung
 *
 * An API providing master data for German railway stations by DB Station&Service AG.
 *
 * The version of the OpenAPI document: 2.2.01
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Aufgabentraeger
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AufgabentraegerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Aufgabentraeger
        //private Aufgabentraeger instance;

        public AufgabentraegerTests()
        {
            // TODO uncomment below to create an instance of Aufgabentraeger
            //instance = new Aufgabentraeger();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Aufgabentraeger
        /// </summary>
        [Fact]
        public void AufgabentraegerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Aufgabentraeger
            //Assert.IsInstanceOfType<Aufgabentraeger> (instance, "variable 'instance' is a Aufgabentraeger");
        }


        /// <summary>
        /// Test the property 'Shortname'
        /// </summary>
        [Fact]
        public void ShortnameTest()
        {
            // TODO unit test for the property 'Shortname'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
