/* 
 * Stationsdatenbereitstellung
 *
 * An API providing master data for German railway stations by DB Station&Service AG.
 *
 * The version of the OpenAPI document: 2.2.01
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing EVANumber
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EVANumberTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EVANumber
        //private EVANumber instance;

        public EVANumberTests()
        {
            // TODO uncomment below to create an instance of EVANumber
            //instance = new EVANumber();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EVANumber
        /// </summary>
        [Fact]
        public void EVANumberInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EVANumber
            //Assert.IsInstanceOfType<EVANumber> (instance, "variable 'instance' is a EVANumber");
        }


        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'IsMain'
        /// </summary>
        [Fact]
        public void IsMainTest()
        {
            // TODO unit test for the property 'IsMain'
        }
        /// <summary>
        /// Test the property 'GeographicCoordinate'
        /// </summary>
        [Fact]
        public void GeographicCoordinateTest()
        {
            // TODO unit test for the property 'GeographicCoordinate'
        }

    }

}
