/* 
 * Stationsdatenbereitstellung
 *
 * An API providing master data for German railway stations by DB Station&Service AG.
 *
 * The version of the OpenAPI document: 2.2.01
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing GeographicPoint
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeographicPointTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GeographicPoint
        //private GeographicPoint instance;

        public GeographicPointTests()
        {
            // TODO uncomment below to create an instance of GeographicPoint
            //instance = new GeographicPoint();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeographicPoint
        /// </summary>
        [Fact]
        public void GeographicPointInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GeographicPoint
            //Assert.IsInstanceOfType<GeographicPoint> (instance, "variable 'instance' is a GeographicPoint");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Coordinates'
        /// </summary>
        [Fact]
        public void CoordinatesTest()
        {
            // TODO unit test for the property 'Coordinates'
        }

    }

}
