/* 
 * Stationsdatenbereitstellung
 *
 * An API providing master data for German railway stations by DB Station&Service AG.
 *
 * The version of the OpenAPI document: 2.2.01
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing OpeningHours
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OpeningHoursTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OpeningHours
        //private OpeningHours instance;

        public OpeningHoursTests()
        {
            // TODO uncomment below to create an instance of OpeningHours
            //instance = new OpeningHours();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OpeningHours
        /// </summary>
        [Fact]
        public void OpeningHoursInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OpeningHours
            //Assert.IsInstanceOfType<OpeningHours> (instance, "variable 'instance' is a OpeningHours");
        }


        /// <summary>
        /// Test the property 'FromTime'
        /// </summary>
        [Fact]
        public void FromTimeTest()
        {
            // TODO unit test for the property 'FromTime'
        }
        /// <summary>
        /// Test the property 'ToTime'
        /// </summary>
        [Fact]
        public void ToTimeTest()
        {
            // TODO unit test for the property 'ToTime'
        }

    }

}
