/* 
 * Stationsdatenbereitstellung
 *
 * An API providing master data for German railway stations by DB Station&Service AG.
 *
 * The version of the OpenAPI document: 2.2.01
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Partial
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartialTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Partial
        //private Partial instance;

        public PartialTests()
        {
            // TODO uncomment below to create an instance of Partial
            //instance = new Partial();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Partial
        /// </summary>
        [Fact]
        public void PartialInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Partial
            //Assert.IsInstanceOfType<Partial> (instance, "variable 'instance' is a Partial");
        }



    }

}
