/* 
 * Stationsdatenbereitstellung
 *
 * An API providing master data for German railway stations by DB Station&Service AG.
 *
 * The version of the OpenAPI document: 2.2.01
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Regionalbereich
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegionalbereichTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Regionalbereich
        //private Regionalbereich instance;

        public RegionalbereichTests()
        {
            // TODO uncomment below to create an instance of Regionalbereich
            //instance = new Regionalbereich();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Regionalbereich
        /// </summary>
        [Fact]
        public void RegionalbereichInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Regionalbereich
            //Assert.IsInstanceOfType<Regionalbereich> (instance, "variable 'instance' is a Regionalbereich");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ShortName'
        /// </summary>
        [Fact]
        public void ShortNameTest()
        {
            // TODO unit test for the property 'ShortName'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }

    }

}
