/* 
 * Stationsdatenbereitstellung
 *
 * An API providing master data for German railway stations by DB Station&Service AG.
 *
 * The version of the OpenAPI document: 2.2.01
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing RiL100Identifier
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RiL100IdentifierTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RiL100Identifier
        //private RiL100Identifier instance;

        public RiL100IdentifierTests()
        {
            // TODO uncomment below to create an instance of RiL100Identifier
            //instance = new RiL100Identifier();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RiL100Identifier
        /// </summary>
        [Fact]
        public void RiL100IdentifierInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RiL100Identifier
            //Assert.IsInstanceOfType<RiL100Identifier> (instance, "variable 'instance' is a RiL100Identifier");
        }


        /// <summary>
        /// Test the property 'RilIdentifier'
        /// </summary>
        [Fact]
        public void RilIdentifierTest()
        {
            // TODO unit test for the property 'RilIdentifier'
        }
        /// <summary>
        /// Test the property 'IsMain'
        /// </summary>
        [Fact]
        public void IsMainTest()
        {
            // TODO unit test for the property 'IsMain'
        }
        /// <summary>
        /// Test the property 'HasSteamPermission'
        /// </summary>
        [Fact]
        public void HasSteamPermissionTest()
        {
            // TODO unit test for the property 'HasSteamPermission'
        }
        /// <summary>
        /// Test the property 'GeographicCoordinate'
        /// </summary>
        [Fact]
        public void GeographicCoordinateTest()
        {
            // TODO unit test for the property 'GeographicCoordinate'
        }

    }

}
