/* 
 * Stationsdatenbereitstellung
 *
 * An API providing master data for German railway stations by DB Station&Service AG.
 *
 * The version of the OpenAPI document: 2.2.01
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Schedule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScheduleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Schedule
        //private Schedule instance;

        public ScheduleTests()
        {
            // TODO uncomment below to create an instance of Schedule
            //instance = new Schedule();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Schedule
        /// </summary>
        [Fact]
        public void ScheduleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Schedule
            //Assert.IsInstanceOfType<Schedule> (instance, "variable 'instance' is a Schedule");
        }


        /// <summary>
        /// Test the property 'Monday'
        /// </summary>
        [Fact]
        public void MondayTest()
        {
            // TODO unit test for the property 'Monday'
        }
        /// <summary>
        /// Test the property 'Tuesday'
        /// </summary>
        [Fact]
        public void TuesdayTest()
        {
            // TODO unit test for the property 'Tuesday'
        }
        /// <summary>
        /// Test the property 'Wednesday'
        /// </summary>
        [Fact]
        public void WednesdayTest()
        {
            // TODO unit test for the property 'Wednesday'
        }
        /// <summary>
        /// Test the property 'Thursday'
        /// </summary>
        [Fact]
        public void ThursdayTest()
        {
            // TODO unit test for the property 'Thursday'
        }
        /// <summary>
        /// Test the property 'Friday'
        /// </summary>
        [Fact]
        public void FridayTest()
        {
            // TODO unit test for the property 'Friday'
        }
        /// <summary>
        /// Test the property 'Saturday'
        /// </summary>
        [Fact]
        public void SaturdayTest()
        {
            // TODO unit test for the property 'Saturday'
        }
        /// <summary>
        /// Test the property 'Sunday'
        /// </summary>
        [Fact]
        public void SundayTest()
        {
            // TODO unit test for the property 'Sunday'
        }
        /// <summary>
        /// Test the property 'Holiday'
        /// </summary>
        [Fact]
        public void HolidayTest()
        {
            // TODO unit test for the property 'Holiday'
        }

    }

}
