/* 
 * Stationsdatenbereitstellung
 *
 * An API providing master data for German railway stations by DB Station&Service AG.
 *
 * The version of the OpenAPI document: 2.2.01
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Station
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Station
        //private Station instance;

        public StationTests()
        {
            // TODO uncomment below to create an instance of Station
            //instance = new Station();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Station
        /// </summary>
        [Fact]
        public void StationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Station
            //Assert.IsInstanceOfType<Station> (instance, "variable 'instance' is a Station");
        }


        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'MailingAdress'
        /// </summary>
        [Fact]
        public void MailingAdressTest()
        {
            // TODO unit test for the property 'MailingAdress'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'PriceCategory'
        /// </summary>
        [Fact]
        public void PriceCategoryTest()
        {
            // TODO unit test for the property 'PriceCategory'
        }
        /// <summary>
        /// Test the property 'FederalState'
        /// </summary>
        [Fact]
        public void FederalStateTest()
        {
            // TODO unit test for the property 'FederalState'
        }
        /// <summary>
        /// Test the property 'HasParking'
        /// </summary>
        [Fact]
        public void HasParkingTest()
        {
            // TODO unit test for the property 'HasParking'
        }
        /// <summary>
        /// Test the property 'HasBicycleParking'
        /// </summary>
        [Fact]
        public void HasBicycleParkingTest()
        {
            // TODO unit test for the property 'HasBicycleParking'
        }
        /// <summary>
        /// Test the property 'HasPublicFacilities'
        /// </summary>
        [Fact]
        public void HasPublicFacilitiesTest()
        {
            // TODO unit test for the property 'HasPublicFacilities'
        }
        /// <summary>
        /// Test the property 'HasLockerSystem'
        /// </summary>
        [Fact]
        public void HasLockerSystemTest()
        {
            // TODO unit test for the property 'HasLockerSystem'
        }
        /// <summary>
        /// Test the property 'HasLocalPublicTransport'
        /// </summary>
        [Fact]
        public void HasLocalPublicTransportTest()
        {
            // TODO unit test for the property 'HasLocalPublicTransport'
        }
        /// <summary>
        /// Test the property 'HasTaxiRank'
        /// </summary>
        [Fact]
        public void HasTaxiRankTest()
        {
            // TODO unit test for the property 'HasTaxiRank'
        }
        /// <summary>
        /// Test the property 'HasTravelNecessities'
        /// </summary>
        [Fact]
        public void HasTravelNecessitiesTest()
        {
            // TODO unit test for the property 'HasTravelNecessities'
        }
        /// <summary>
        /// Test the property 'HasSteplessAccess'
        /// </summary>
        [Fact]
        public void HasSteplessAccessTest()
        {
            // TODO unit test for the property 'HasSteplessAccess'
        }
        /// <summary>
        /// Test the property 'HasMobilityService'
        /// </summary>
        [Fact]
        public void HasMobilityServiceTest()
        {
            // TODO unit test for the property 'HasMobilityService'
        }
        /// <summary>
        /// Test the property 'HasWiFi'
        /// </summary>
        [Fact]
        public void HasWiFiTest()
        {
            // TODO unit test for the property 'HasWiFi'
        }
        /// <summary>
        /// Test the property 'HasTravelCenter'
        /// </summary>
        [Fact]
        public void HasTravelCenterTest()
        {
            // TODO unit test for the property 'HasTravelCenter'
        }
        /// <summary>
        /// Test the property 'HasRailwayMission'
        /// </summary>
        [Fact]
        public void HasRailwayMissionTest()
        {
            // TODO unit test for the property 'HasRailwayMission'
        }
        /// <summary>
        /// Test the property 'HasDBLounge'
        /// </summary>
        [Fact]
        public void HasDBLoungeTest()
        {
            // TODO unit test for the property 'HasDBLounge'
        }
        /// <summary>
        /// Test the property 'HasLostAndFound'
        /// </summary>
        [Fact]
        public void HasLostAndFoundTest()
        {
            // TODO unit test for the property 'HasLostAndFound'
        }
        /// <summary>
        /// Test the property 'HasCarRental'
        /// </summary>
        [Fact]
        public void HasCarRentalTest()
        {
            // TODO unit test for the property 'HasCarRental'
        }
        /// <summary>
        /// Test the property 'EvaNumbers'
        /// </summary>
        [Fact]
        public void EvaNumbersTest()
        {
            // TODO unit test for the property 'EvaNumbers'
        }
        /// <summary>
        /// Test the property 'RiL100Identifiers'
        /// </summary>
        [Fact]
        public void RiL100IdentifiersTest()
        {
            // TODO unit test for the property 'RiL100Identifiers'
        }
        /// <summary>
        /// Test the property 'TimetableOffice'
        /// </summary>
        [Fact]
        public void TimetableOfficeTest()
        {
            // TODO unit test for the property 'TimetableOffice'
        }
        /// <summary>
        /// Test the property 'StationManagement'
        /// </summary>
        [Fact]
        public void StationManagementTest()
        {
            // TODO unit test for the property 'StationManagement'
        }
        /// <summary>
        /// Test the property 'LocalServiceStaff'
        /// </summary>
        [Fact]
        public void LocalServiceStaffTest()
        {
            // TODO unit test for the property 'LocalServiceStaff'
        }
        /// <summary>
        /// Test the property 'DBinformation'
        /// </summary>
        [Fact]
        public void DBinformationTest()
        {
            // TODO unit test for the property 'DBinformation'
        }
        /// <summary>
        /// Test the property 'Regionalbereich'
        /// </summary>
        [Fact]
        public void RegionalbereichTest()
        {
            // TODO unit test for the property 'Regionalbereich'
        }
        /// <summary>
        /// Test the property 'Szentrale'
        /// </summary>
        [Fact]
        public void SzentraleTest()
        {
            // TODO unit test for the property 'Szentrale'
        }
        /// <summary>
        /// Test the property 'Aufgabentraeger'
        /// </summary>
        [Fact]
        public void AufgabentraegerTest()
        {
            // TODO unit test for the property 'Aufgabentraeger'
        }

    }

}
