/* 
 * Stationsdatenbereitstellung
 *
 * An API providing master data for German railway stations by DB Station&Service AG.
 *
 * The version of the OpenAPI document: 2.2.01
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing SZentrale
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SZentraleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SZentrale
        //private SZentrale instance;

        public SZentraleTests()
        {
            // TODO uncomment below to create an instance of SZentrale
            //instance = new SZentrale();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SZentrale
        /// </summary>
        [Fact]
        public void SZentraleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SZentrale
            //Assert.IsInstanceOfType<SZentrale> (instance, "variable 'instance' is a SZentrale");
        }


        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PublicPhoneNumber'
        /// </summary>
        [Fact]
        public void PublicPhoneNumberTest()
        {
            // TODO unit test for the property 'PublicPhoneNumber'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'PublicFaxNumber'
        /// </summary>
        [Fact]
        public void PublicFaxNumberTest()
        {
            // TODO unit test for the property 'PublicFaxNumber'
        }
        /// <summary>
        /// Test the property 'InternalPhoneNumber'
        /// </summary>
        [Fact]
        public void InternalPhoneNumberTest()
        {
            // TODO unit test for the property 'InternalPhoneNumber'
        }
        /// <summary>
        /// Test the property 'InternalFaxNumber'
        /// </summary>
        [Fact]
        public void InternalFaxNumberTest()
        {
            // TODO unit test for the property 'InternalFaxNumber'
        }
        /// <summary>
        /// Test the property 'MobilePhoneNumber'
        /// </summary>
        [Fact]
        public void MobilePhoneNumberTest()
        {
            // TODO unit test for the property 'MobilePhoneNumber'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
