/* 
 * Stationsdatenbereitstellung
 *
 * An API providing master data for German railway stations by DB Station&Service AG.
 *
 * The version of the OpenAPI document: 2.2.01
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing SZentraleRef
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SZentraleRefTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SZentraleRef
        //private SZentraleRef instance;

        public SZentraleRefTests()
        {
            // TODO uncomment below to create an instance of SZentraleRef
            //instance = new SZentraleRef();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SZentraleRef
        /// </summary>
        [Fact]
        public void SZentraleRefInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SZentraleRef
            //Assert.IsInstanceOfType<SZentraleRef> (instance, "variable 'instance' is a SZentraleRef");
        }


        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PublicPhoneNumber'
        /// </summary>
        [Fact]
        public void PublicPhoneNumberTest()
        {
            // TODO unit test for the property 'PublicPhoneNumber'
        }

    }

}
