/* 
 * Stationsdatenbereitstellung
 *
 * An API providing master data for German railway stations by DB Station&Service AG.
 *
 * The version of the OpenAPI document: 2.2.01
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// local public sector entity, responsible for short distance public transport in a specific area
    /// </summary>
    [DataContract]
    public partial class Aufgabentraeger :  IEquatable<Aufgabentraeger>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Aufgabentraeger" /> class.
        /// </summary>
        /// <param name="shortname">unique identifier.</param>
        /// <param name="name">full name of Aufgabentraeger.</param>
        public Aufgabentraeger(string shortname = default(string), string name = default(string))
        {
            this.Shortname = shortname;
            this.Name = name;
        }
        
        /// <summary>
        /// unique identifier
        /// </summary>
        /// <value>unique identifier</value>
        [DataMember(Name="shortname", EmitDefaultValue=false)]
        public string Shortname { get; set; }

        /// <summary>
        /// full name of Aufgabentraeger
        /// </summary>
        /// <value>full name of Aufgabentraeger</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Aufgabentraeger {\n");
            sb.Append("  Shortname: ").Append(Shortname).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Aufgabentraeger);
        }

        /// <summary>
        /// Returns true if Aufgabentraeger instances are equal
        /// </summary>
        /// <param name="input">Instance of Aufgabentraeger to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Aufgabentraeger input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Shortname == input.Shortname ||
                    (this.Shortname != null &&
                    this.Shortname.Equals(input.Shortname))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Shortname != null)
                    hashCode = hashCode * 59 + this.Shortname.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
