/* 
 * Stationsdatenbereitstellung
 *
 * An API providing master data for German railway stations by DB Station&Service AG.
 *
 * The version of the OpenAPI document: 2.2.01
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines Partial
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Partial
    {
        /// <summary>
        /// Enum Yes for value: yes
        /// </summary>
        [EnumMember(Value = "yes")]
        Yes = 1,

        /// <summary>
        /// Enum No for value: no
        /// </summary>
        [EnumMember(Value = "no")]
        No = 2,

        /// <summary>
        /// Enum Partial for value: partial
        /// </summary>
        [EnumMember(Value = "partial")]
        Partial = 3

    }

}
